### ISSUE TITLE
Windows 10 "Do you want to run?" - Smart Screen

### ISSUE THREAD

**Issue by simon-ourmachinery** [copperspice/doxypressapp#3]
When running the app I get this:
![image](https://user-images.githubusercontent.com/70658708/99656609-68974000-2a5d-11eb-9aac-5e997891784c.png)

**Comment by bgeller** [comment]
This is not a message from DoxyPress.  It looks like Windows Smart Screen (AV program) is blocking something.

Were you successfully able to download the "setup-doxypress-1.4.0-x64.exe" file?
Did you run the setup?  Any issues during setup?
Did you install to the default location? 
If you run "DoxyPress -v" from a command line what happens?

Let us know a bit more so we can help you figure out what is happening on your computer.  We have an office computer setup with Windows 10 with zero issues. 

Barbara

**Comment by simon-ourmachinery** [comment]
Hi @bgeller  I am sorry I should have been more specific...

So I got this error message when I tried to run the setup. `setup-doxypress-1.4.0-x64.exe`

**Comment by bgeller** [comment]
When installing on Windows you can encounter AV issues.  This implies the setup program will not run or is unable to write to the path you have specified.  So we know this is not a DoxyPressApp or DoxyPress issue, this is some install issue.  I would suggest you temporarily turn off your AV to allow the setup program to run.  The setup program we are using is a very well known and trusted product.

I did a bit of research for you. Here is a quote from a PCWorld article. 

"On the "Microsoft Defender Screen" click the "More info" link at the end of the warning paragraph. When you click that, you then see a window with a new option: Run anyway. Click that and you are all set. The program will start installing as normal." 

Barbara

**Comment by simon-ourmachinery** [comment]
Yes I did this. I just wanted to raise awareness that if the software has not been certified that the smart screen might not disapear later on and new users will have this always.

I assume that the installer software signs automatically. Therefore sorry for this issue.

My sources:
- https://docs.microsoft.com/en-gb/archive/blogs/ie/microsoft-smartscreen-extended-validation-ev-code-signing-certificates
- https://stackoverflow.com/questions/12311203/how-to-pass-the-smart-screen-on-win8-when-install-a-signed-application
- https://www.codeproject.com/Questions/555248/Willplussigningplusanplusexecutablepluspreventplus
- https://mkaz.blog/code/code-signing-a-windows-application/ (most recent one)
